### ISSUE TITLE
Feature:

### ISSUE THREAD

**Issue by zbanga** [wai-i/Pair-Trading-Reinforcement-Learning#1]
Hi, 

I have implemented for FX and the results look decent for Pairs. I have noticed that if P values are high they don't seem to result in positive out of sample testing. But even if P values of 0.5 or so hold up, although they don't trade that often. 

Would you have an email so I could show you the results or could collaborate to make this better?

**Comment by LinuxpowerLudo** [comment]
> 
> 
> Hi,
> 
> I have implemented for FX and the results look decent for Pairs. I have noticed that if P values are high they don't seem to result in positive out of sample testing. But even if P values of 0.5 or so hold up, although they don't trade that often.
> 
> Would you have an email so I could show you the results or could collaborate to make this better?

Hello Zbanga,

Have you perform the code in live (demo account) on FX market ? You have found cointegre pairs on fx ? 

Regards
Ludo.

**Comment by zbanga** [comment]
Hi LinuxpowerLudo,

I have converted the different equity pairs to different FX pairs on Google Colab. I am still understanding the code and how to convert it to live trading. But the results so far look very promising. 

Kind Regards,
Zbanga

**Comment by zbanga** [comment]
Although I still not confirm if there is or isn't any data leakage.

**Comment by LinuxpowerLudo** [comment]
Yes that's why I'm trying to make a RunningScript_live.py with only data not seen with the model saved during the training script but I don't have a good command of tensorflow 🙃

**Comment by zbanga** [comment]
You need to save the model first. Then load the model and feed it new data unseen before. 
https://www.tensorflow.org/guide/saved_model

**Comment by LinuxpowerLudo** [comment]
Yes, I understood the concept well:) 
Thank you for the link.
If I use a saver.restore I need to recreate my RL actions/states variables and the network?

**Comment by zbanga** [comment]
I think they might save the network but your actions/states variables may be gone. Not 100% sure

**Comment by LinuxpowerLudo** [comment]
It's more easy with keras :) :) 
@wai-i if you can help me about load model and test with unseen data :)

**Comment by wai-i** [comment]
@zbanga There is no guarantee that the cointegrated pattern will extend for a (unknown) time frame, not to mention that high p-value is used. The spread could trend up/down even if it is deemed cointegrated for a specific window. Therefore what you may need is to forecast the cointegration relationship which the code does not cover for the time being. 

@LinuxpowerLudo Please try the `restore_model` in the Agent class. For the data just make sure it is cleaned and with format consistent to the sample data.

**Comment by LinuxpowerLudo** [comment]
@wai-i thanks for your feedback ! Yes i set the restore_model with the config_test.yml and restore=True.
but in the current state it cannot be used in live forward test... the fact of using a history and forward indices, the test never goes until the end of the test file.
In addition, during the backtest the spread / beta is recalculated on the sliding window, so the spread changes with each recalculation (maybe false signals).

**Comment by wai-i** [comment]
@LinuxpowerLudo Not sure if I get the first point but I guess for testing you may want to build another routine inside the ContextualBandit and create a testing function which runs after loading the trained TF network. For the second one the spreads are standardized so the beta should be estimated on a similar basis across windows.
