### ISSUE TITLE
EG_Test process question

### ISSUE THREAD

**Issue by milabobo** [wai-i/Pair-Trading-Reinforcement-Learning#3]
Hi, @wai-i , thanks for the nice project, here i have a question:
in `RunningScript.py`, when run `EG_Test.process` after training finish, in `gen_signal` method, we using `spread = self.cal_spread(x, y, is_norm=True)` to calculate spread, which is  then calculated by `resid = (resid - resid.mean()) / resid.std() if is_norm is True else resid`.
Here seems using `future's` data to generate `future's` mean and std, then using this feature to trade, the profit may not be correct?

**Comment by wai-i** [comment]
Hi @milabobo, for the testing, at a particular point of time in the testing data, the standardization applies to calibration only using _historical_ data, while the actual price in _future_ is used for trading. Hope this answers your question.

**Comment by wai-i** [comment]
@milabobo , you're right. Thanks for reminding. Actually I have created a self.resid_mean and self.resid_std in __init__ but missed the implementation. After the following updates:

    def calibrate(self, start, end, cl):
        x, y, _ = self.get_sample(start, end)
        self.p  = self.get_p_value(x, y)
        if self.p < cl:
            resid = self.cal_spread(x, y, is_norm=False)
            self.resid_mean = resid.mean()
            self.resid_std  = resid.std()
            self.run_ols(x, y)

    def cal_spread(self, x, y, is_norm):
        resid = y - x * self.beta
        resid = (resid - self.resid_mean) / self.resid_std if is_norm is True else resid
        return resid

 gen_signal() should now calculate the spread based on the historical mean and stdev.

**Comment by milabobo** [comment]
@wai-i good fix! Looking forward to new test results.
