### ISSUE TITLE
@Part5 - Step "7" sess.close()  SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by cyberslam** [wai-i/Pair-Trading-Reinforcement-Learning#4]
Hi Wai-i,

            First of all I like to congrat to you on providing us a very nice and well thought out RL program for pair-trading to experiment with.

             I started at Part 5 and stopped at Step 5 where I got this error message:

# Create Reinforcement Learning object for training and testing.
1    RL_Train = RL.ContextualBandit(N, config_train, EG_Train)
2    sess = tf.Session()
3    RL_Train.process(sess, save=False, restore=False)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-16-205fc1ff74f6> in <module>()
      1 RL_Train = RL.ContextualBandit(N, config_train, EG_Train)
      2 sess = tf.Session()
---> 3 RL_Train.process(sess, save=False, restore=False)

/content/Pair-Trading-Reinforcement-Learning-master/MAIN/Reinforcement.py in process(self, session, save, restore)
     73                 self.state_space.process()
     74                 self.action_space.process()
---> 75                 self.reward_engine.process()
     76                 self.buffering()
     77                 self.update_network()

/content/Pair-Trading-Reinforcement-Learning-master/PROCESSOR/MachineLearning.py in process(self)
     61 
     62     def process(self):
---> 63         reward, record = self._get_reward()
     64         self.agent.data['ENGINE_REWARD'] = reward
     65         self.agent.data['ENGINE_RECORD'] = record

/content/Pair-Trading-Reinforcement-Learning-master/PROCESSOR/MachineLearning.py in _get_reward(self)
     68         state  = self.agent.data['ENGINE_STATE']
     69         action = self.agent.data['ENGINE_ACTION']
---> 70         self.engine.process(**state, **action)
     71         return self.engine.reward, self.engine.record
     72 

/content/Pair-Trading-Reinforcement-Learning-master/STRATEGY/Cointegration.py in process(self, n_hist, n_forward, trade_th, stop_loss, cl, transaction_cost, index, **kwargs)
    195         index = random.randint(n_hist, len(self.x) - n_forward) if index is None else index
    196         start_hist, end_hist, start_forward, end_forward = self.get_indices(index, n_hist, n_forward)
--> 197         self.calibrate(start_hist, end_hist, cl)
    198         self.reward = 0
    199         self.record = None

/content/Pair-Trading-Reinforcement-Learning-master/STRATEGY/Cointegration.py in calibrate(self, start, end, cl)
     82         self.p  = self.get_p_value(x, y)
     83         if self.p < cl:
---> 84             resid = self.cal_spread(x, y, is_norm=False)
     85             self.resid_mean = resid.mean()
     86             self.resid_std  = resid.std()

/content/Pair-Trading-Reinforcement-Learning-master/STRATEGY/Cointegration.py in cal_spread(self, x, y, is_norm)
     58 
     59     def cal_spread(self, x, y, is_norm):
---> 60         resid = y - x * self.beta
     61         resid = (resid - self.resid_mean) / self.resid_std if is_norm is True else resid
     62         return resid

TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

   
            Can you enlighten me on how to correct this minor error.   Many thanks.

**Comment by wai-i** [comment]
Hi @cyberslam,

Thanks for raising it. I think it's because _run_ols_ is called after _cal_spread_ and self.beta was initialized as None.

I have updated the function as below:

    def calibrate(self, start, end, cl):
        x, y, _ = self.get_sample(start, end)
        self.p  = self.get_p_value(x, y)
        if self.p < cl:
            self.run_ols(x, y) # call run_ols before cal_spread
            resid = self.cal_spread(x, y, is_norm=False)
            self.resid_mean = resid.mean()
            self.resid_std  = resid.std()

Hope this works for you.

**Comment by cyberslam** [comment]
Hi Wai-i,

              Thank you for getting back to me so soon.  I have continued on with your revised corrections
and able to proceed further on Part 5 of Step 5.  The program completed 10 epochs and 110,000 steps in ~45 minutes and ended with no error and the following:  (some "divided by zero" warnings)

Counter [Epoch]: 9 steps processed...
Counter [Iteration]: 101000 steps processed...
Counter [Iteration]: 102000 steps processed...
Counter [Iteration]: 103000 steps processed...
Counter [Iteration]: 104000 steps processed...
Counter [Iteration]: 105000 steps processed...
/usr/local/lib/python3.6/dist-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: divide by zero encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/usr/local/lib/python3.6/dist-packages/statsmodels/regression/linear_model.py:867: RuntimeWarning: divide by zero encountered in log
  llf = -nobs2*np.log(2*np.pi) - nobs2*np.log(ssr / nobs) - nobs2
/usr/local/lib/python3.6/dist-packages/statsmodels/base/model.py:1294: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/usr/local/lib/python3.6/dist-packages/statsmodels/tsa/stattools.py:1432: CollinearityWarning: y0 and y1 are (almost) perfectly colinear.Cointegration test is not reliable in this case.
  CollinearityWarning)
Counter [Iteration]: 106000 steps processed...
Counter [Iteration]: 107000 steps processed...
Counter [Iteration]: 108000 steps processed...
Counter [Iteration]: 109000 steps processed...
Counter [Iteration]: 110000 steps processed...
Counter [Iteration]: Process completed.
Counter [Epoch]: 10 steps processed...
Counter [Epoch]: Process completed.

           In "Step 6", I have to add the following since I didn't start the program like you did:

import seaborn as sns

Here's my entire Step 6 listing:

# Extract training results

# added this to avoid missing sns error
import seaborn as sns

action = RL_Train.recorder.record['NETWORK_ACTION']
reward = RL_Train.recorder.record['ENGINE_REWARD']
print(np.mean(reward))

df1 = pd.DataFrame()
df1['action'] = action
df1['reward'] = reward
mean_reward = df1.groupby('action').mean()
sns.distplot(mean_reward)

              The resulting graph is NOT the same as yours: (hope you can see it)

-0.05135269117724864
![image](https://user-images.githubusercontent.com/9262262/70159418-b741a380-166d-11ea-8878-8ae4d4eb0743.png)


             I then proceed to "Step 7" (test trades) and got an error: (showing the first 2 lines and last 5 lines of the program)

# Extract the optimal action
[opt_action] = sess.run([RL_Train.output], feed_dict=RL_Train.feed_dict)
....
....
# Plot the testing result
pnl['PnL'] = (pnl['Trade_Profit'] - pnl['Cost']).cumsum()
plt.plot(pnl['PnL'])
plt.plot(pnl['N_Trade']
sess.close()

Here's the error message:
File "<ipython-input-12-71cada74c346>", line 46
    sess.close()
       ^
SyntaxError: invalid syntax

              The line #46 was this line:
plt.plot(pnl['N_Trade']

               It appears that the "sess.close()" was not properly ending this segment of the program.

             Please have a look and show me how to correct this.  Many thanks Wai-i.


cyberslam

**Comment by cyberslam** [comment]
Hi Wei-i,

           I reran your revised code today and got the same chart as you have in Part 5 - "Step 6".  
However, I still have the error most likely due to the End of File issue on the second last line
and produced:   sess.close()  - syntax error.

            My exact code ran was as followed:


# Extract the optimal action
[opt_action] = sess.run([RL_Train.output], feed_dict=RL_Train.feed_dict)
opt_action = np.argmax(opt_action)
action_dict = RL_Train.action_space.convert(opt_action, 'index_to_dict')
indices = range(601, len(EG_Test.x) - 1200)

# Create result table
pnl = pd.DataFrame()
pnl['Time'] = EG_Test.timestamp
pnl['Trade_Profit'] = 0
pnl['Cost'] = 0
pnl['N_Trade'] = 0

# Test by trading continuously
import warnings
warnings.filterwarnings('ignore')

for i in indices:
  
    if i % 100 == 0:
        print(i)
    EG_Test.process(index=i, transaction_cost=0.001, **action_dict)
    trade_record = EG_Test.record
    
    if (trade_record is not None) and (len(trade_record) > 0):
        print('value at {}'.format(i))
        trade_record = pd.DataFrame(trade_record)
        trade_cost   = trade_record.groupby('trade_time')['trade_cost'].sum()
        close_cost   = trade_record.groupby('close_time')['close_cost'].sum()
        profit       = trade_record.groupby('close_time')['profit'].sum()
        open_pos     = trade_record.groupby('trade_time')['long_short'].sum()
        close_pos    = trade_record.groupby('close_time')['long_short'].sum() * -1

        pnl['Cost'].loc[pnl['Time'].isin(trade_cost.index)] += trade_cost.values
        pnl['Cost'].loc[pnl['Time'].isin(close_cost.index)] += close_cost.values
        pnl['Trade_Profit'].loc[pnl['Time'].isin(close_cost.index)] += profit.values
        pnl['N_Trade'].loc[pnl['Time'].isin(trade_cost.index)] += open_pos.values
        pnl['N_Trade'].loc[pnl['Time'].isin(close_cost.index)] += close_pos.values

        
warnings.filterwarnings(action='once')

# Plot the testing result
pnl['PnL'] = (pnl['Trade_Profit'] - pnl['Cost']).cumsum()
plt.plot(pnl['PnL'])
plt.plot(pnl['N_Trade']
sess.close()

               The error produced as:

File "<ipython-input-18-71cada74c346>", line 46
    sess.close()
       ^
SyntaxError: invalid syntax

                Please have a look at this.  Many thanks Wei-i.

Cyberslam
