### ISSUE TITLE
sess.close()  SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by cyberslam** [wai-i/Pair-Trading-Reinforcement-Learning#5]
Hi Wei-i,

       I reran your revised code today and got the same chart as you have in Part 5 - "Step 6".  
However, I still have the error most likely due to the End of File issue on the second last line
and produced: sess.close() - syntax error.

        My exact code ran was as followed:
Extract the optimal action
[opt_action] = sess.run([RL_Train.output], feed_dict=RL_Train.feed_dict)
opt_action = np.argmax(opt_action)
action_dict = RL_Train.action_space.convert(opt_action, 'index_to_dict')
indices = range(601, len(EG_Test.x) - 1200)

Create result table
pnl = pd.DataFrame()
pnl['Time'] = EG_Test.timestamp
pnl['Trade_Profit'] = 0
pnl['Cost'] = 0
pnl['N_Trade'] = 0

Test by trading continuously
import warnings
warnings.filterwarnings('ignore')

for i in indices:

if i % 100 == 0:
    print(i)
EG_Test.process(index=i, transaction_cost=0.001, **action_dict)
trade_record = EG_Test.record

if (trade_record is not None) and (len(trade_record) > 0):
    print('value at {}'.format(i))
    trade_record = pd.DataFrame(trade_record)
    trade_cost   = trade_record.groupby('trade_time')['trade_cost'].sum()
    close_cost   = trade_record.groupby('close_time')['close_cost'].sum()
    profit       = trade_record.groupby('close_time')['profit'].sum()
    open_pos     = trade_record.groupby('trade_time')['long_short'].sum()
    close_pos    = trade_record.groupby('close_time')['long_short'].sum() * -1

    pnl['Cost'].loc[pnl['Time'].isin(trade_cost.index)] += trade_cost.values
    pnl['Cost'].loc[pnl['Time'].isin(close_cost.index)] += close_cost.values
    pnl['Trade_Profit'].loc[pnl['Time'].isin(close_cost.index)] += profit.values
    pnl['N_Trade'].loc[pnl['Time'].isin(trade_cost.index)] += open_pos.values
    pnl['N_Trade'].loc[pnl['Time'].isin(close_cost.index)] += close_pos.values
warnings.filterwarnings(action='once')

Plot the testing result
pnl['PnL'] = (pnl['Trade_Profit'] - pnl['Cost']).cumsum()
plt.plot(pnl['PnL'])
plt.plot(pnl['N_Trade']
sess.close()

           The error produced as:
File "", line 46
sess.close()
^
SyntaxError: invalid syntax

            Please have a look at this.  Many thanks Wei-i.
Cyberslam

**Comment by wai-i** [comment]
I guess it's because there is a missing closing bracket in line 45?

plt.plot(pnl['N_Trade'] <-----
sess.close()
