### ISSUE TITLE
Part5: "Step 7"  NameError: name 'EG_Test' is not defined

### ISSUE THREAD

**Issue by cyberslam** [wai-i/Pair-Trading-Reinforcement-Learning#6]
Hi Wei-i,

           In Part 5 "Step 6", I obtained a different looking chart than your with the following listing:

Step 6: Extract the records from the learning object and perform testing analysis

# Extract training results

# cyberslam added this
import seaborn as sns

action = RL_Train.recorder.record['NETWORK_ACTION']
reward = RL_Train.recorder.record['ENGINE_REWARD']
print(np.mean(reward))

df1 = pd.DataFrame()
df1['action'] = action
df1['reward'] = reward
mean_reward = df1.groupby('action').mean()
sns.distplot(mean_reward)

-0.009319296095334946
<matplotlib.axes._subplots.AxesSubplot at 0x7facd2a100f0>

In "Step 7" I have corrected the listing as follows:

The following test trade across every minute using the optimal action obtained from the training result, excluding the maximum possible historical window and trading window:

# Extract the optimal action
[opt_action] = sess.run([RL_Train.output], feed_dict=RL_Train.feed_dict)
opt_action = np.argmax(opt_action)
action_dict = RL_Train.action_space.convert(opt_action, 'index_to_dict')
indices = range(601, len(EG_Test.x) - 1200)

# Create result table
pnl = pd.DataFrame()
pnl['Time'] = EG_Test.timestamp
pnl['Trade_Profit'] = 0
pnl['Cost'] = 0
pnl['N_Trade'] = 0

# Test by trading continuously
import warnings
warnings.filterwarnings('ignore')

for i in indices:
  
    if i % 100 == 0:
        print(i)
    EG_Test.process(index=i, transaction_cost=0.001, **action_dict)
    trade_record = EG_Test.record
    
    if (trade_record is not None) and (len(trade_record) > 0):
        print('value at {}'.format(i))
        trade_record = pd.DataFrame(trade_record)
        trade_cost   = trade_record.groupby('trade_time')['trade_cost'].sum()
        close_cost   = trade_record.groupby('close_time')['close_cost'].sum()
        profit       = trade_record.groupby('close_time')['profit'].sum()
        open_pos     = trade_record.groupby('trade_time')['long_short'].sum()
        close_pos    = trade_record.groupby('close_time')['long_short'].sum() * -1

        pnl['Cost'].loc[pnl['Time'].isin(trade_cost.index)] += trade_cost.values
        pnl['Cost'].loc[pnl['Time'].isin(close_cost.index)] += close_cost.values
        pnl['Trade_Profit'].loc[pnl['Time'].isin(close_cost.index)] += profit.values
        pnl['N_Trade'].loc[pnl['Time'].isin(trade_cost.index)] += open_pos.values
        pnl['N_Trade'].loc[pnl['Time'].isin(close_cost.index)] += close_pos.values

        
warnings.filterwarnings(action='once')

# Plot the testing result
pnl['PnL'] = (pnl['Trade_Profit'] - pnl['Cost']).cumsum()
plt.plot(pnl['PnL'])
plt.plot(pnl['N_Trade'])
sess.close()

           However, I received an error:

NameError                                 Traceback (most recent call last)
<ipython-input-12-c74546108513> in <module>()
      2 opt_action = np.argmax(opt_action)
      3 action_dict = RL_Train.action_space.convert(opt_action, 'index_to_dict')
----> 4 indices = range(601, len(EG_Test.x) - 1200)
      5 
      6 # Create result table

NameError: name 'EG_Test' is not defined

                  Thanks Wei-i for looking into that.  I was using Google Colab notebook.

Cyberslam

**Comment by cyberslam** [comment]
![image](https://user-images.githubusercontent.com/9262262/70486347-59b2ba00-1aa6-11ea-8e3e-dfdfa5938510.png)

**Comment by wai-i** [comment]
For this I am not very sure since I could run from the beginning. Maybe you just missed the line that create EG_Test? I guess this is more about the practice than the issue of the code.

**Comment by cyberslam** [comment]
Hi Wai-i,
             Can you give me a copy of your COMPLETE PROGRAM LISTING?  It just want to make sure the program runs as you indicated.  Thanks in advance Wai-i.

Cheers,

Samuel

**Comment by cyberslam** [comment]
OK.  I was able to run the program without an error - after making a complete program from start to end (7 steps).   However, I didn't get the same result as you do - not even close!

I will just close this issue for now.
